# Event schema

# --- !Ups

CREATE TABLE EVENT (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    STARTS_AT TIMESTAMP NOT NULL,
    ENDS_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NULL,
    PRIMARY KEY (ID)
);

# --- !Downs

DROP TABLE EVENT;