# Location schema

# --- !Ups

CREATE TABLE LOCATION (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(64) NOT NULL,
    ADDRESS VARCHAR (255) NOT NULL,
    CITY VARCHAR(32) NOT NULL,
    ZIP_CODE VARCHAR(32) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    COUNTRY VARCHAR(2) NOT NULL,
    PRIMARY KEY (ID)
);

# --- !Downs

DROP TABLE LOCATION;