# Tag schema

# --- !Ups

CREATE TABLE TAG (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE EVENT_TAG (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  EVENT_ID BIGINT(20),
  TAG_ID BIGINT(20)
);

# --- !Downs

DROP TABLE TAG;
DROP TABLE EVENT_TAG;
