# Add event series

# --- !Ups

CREATE TABLE SERIES (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    EVENT_ID BIGINT(20) NOT NULL,
    DURATION INT,
    STARTS_AT TIMESTAMP NOT NULL,
    ENDS_AT TIMESTAMP,

    FREQ TINYINT,
    BY_DAY VARCHAR(255),
    INTERVAL SMALLINT,

    CREATED_AT TIMESTAMP NULL,
    PRIMARY KEY (ID)
);

# --- !Downs

DROP TABLE SERIES;