# Make series end date required

# --- !Ups

UPDATE SERIES SET ENDS_AT = TIMESTAMPADD(YEAR, 1, STARTS_AT);
ALTER TABLE SERIES MODIFY ENDS_AT TIMESTAMP NULL;

# --- !Downs

ALTER TABLE SERIES MODIFY ENDS_AT TIMESTAMP NOT NULL;
