# Occurrence schema

# --- !Ups

CREATE TABLE OCCURRENCE (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    SERIES_ID BIGINT(20) NOT NULL,
    DATE TIMESTAMP NOT NULL,
    DELETED BIT NOT NULL,
    MODIFIED BIT NOT NULL,
    PRIMARY KEY (ID)
);

# --- !Downs

DROP TABLE OCCURRENCE;